spring.application.name=timecalc

# Server settings
server.port=8080
server.address=localhost

# JPA settings
spring.datasource.url=jdbc:postgresql://localhost:5432/SoftDev
spring.datasource.username=postgres
spring.datasource.password=dan
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs